__author__ = 'iury'
import unittest

'''
Problem

In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.

The reverse complement of a DNA string s is the string sc formed by reversing the symbols of s, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

Given: A DNA string s of length at most 1000 bp.

Return: The reverse complement sc of s.
'''


def reverseComplement(stringDna):
    reverse = ''
    for symbol in stringDna[::-1]:
        if symbol == 'A':
            reverse += 'T'
        if symbol == 'T':
            reverse += 'A'
        if symbol == 'G':
            reverse += 'C'
        if symbol == 'C':
            reverse += 'G'

    return reverse


class Test(unittest.TestCase):
    def test1(self):
        self.assertEquals('ACCGGGTTTT', reverseComplement('AAAACCCGGT'))

    def test2(self):
        self.assertEqual(
            'GCCAAGGCGGTATATACCTGACCGTAGCTGTCAAGTACTCCCTTTAACAACTGACAGTGATATATAGATGTCTGGGACACACCCGTGGTATGCTACCAGTAATCCCTCTGCATTACGGGATCTTGTGTGTACCATGATGACGTGGAGATCCATTCCACGGTTCATAAATCTTGGGAGCGCGTGATATGGCGAGAAAAAATAACAACCTCGTTATTATCATTTACATGCGTTACTAATTGCGTATCGGGGTATTACGGTTCCCTTTGTAGGGGCGTACAGCTCGATGGCCCAAATCTTTTAGACAGAGTATGTACCGATATGGTATGCCCGGACCTCCCATTCTACTGCTCCCGTTAGTCAGCGTATTAATAATCGAGCTAATATTAGAATATCGGTAGTTCACAGGGCGAAACTTTTCCCTAATACGCCGCGCCCGAACATCAGCCTAAGTCACAGGGAGTTTTGTTTTCGCGTAAAATGTGCGCTTATCTCGCCCAACAGTACTCGTTATGATAAGCGTATGCCATGTCGACGGGGAATCTCTGTGCCGTCAGTTCAGAAATGCATAGGTACCGACGGCCGTTTACAAAACAGAAAACACACCCAATTAATGTAGATTGTAACCCACTACCCTACGGGGGTACCAGATGTCGGCCGGAACCCGGAGTTTCGCGGAGACTTACGTCAGCGCGTGGTTTCTAACCATGGCATAGTTTTACTCATCTTCGTTATGAACGCATACACCCCTACCCTCTATTAAGGCGGTCAAGTGCGAGATTGGAAATTGTCAGCACCGAAGGGTTATGCAAGGCAACACTAGTCCCAACATTTAATTCATCATAGGGTCAAAAGCCA',
            reverseComplement(
                'TGGCTTTTGACCCTATGATGAATTAAATGTTGGGACTAGTGTTGCCTTGCATAACCCTTCGGTGCTGACAATTTCCAATCTCGCACTTGACCGCCTTAATAGAGGGTAGGGGTGTATGCGTTCATAACGAAGATGAGTAAAACTATGCCATGGTTAGAAACCACGCGCTGACGTAAGTCTCCGCGAAACTCCGGGTTCCGGCCGACATCTGGTACCCCCGTAGGGTAGTGGGTTACAATCTACATTAATTGGGTGTGTTTTCTGTTTTGTAAACGGCCGTCGGTACCTATGCATTTCTGAACTGACGGCACAGAGATTCCCCGTCGACATGGCATACGCTTATCATAACGAGTACTGTTGGGCGAGATAAGCGCACATTTTACGCGAAAACAAAACTCCCTGTGACTTAGGCTGATGTTCGGGCGCGGCGTATTAGGGAAAAGTTTCGCCCTGTGAACTACCGATATTCTAATATTAGCTCGATTATTAATACGCTGACTAACGGGAGCAGTAGAATGGGAGGTCCGGGCATACCATATCGGTACATACTCTGTCTAAAAGATTTGGGCCATCGAGCTGTACGCCCCTACAAAGGGAACCGTAATACCCCGATACGCAATTAGTAACGCATGTAAATGATAATAACGAGGTTGTTATTTTTTCTCGCCATATCACGCGCTCCCAAGATTTATGAACCGTGGAATGGATCTCCACGTCATCATGGTACACACAAGATCCCGTAATGCAGAGGGATTACTGGTAGCATACCACGGGTGTGTCCCAGACATCTATATATCACTGTCAGTTGTTAAAGGGAGTACTTGACAGCTACGGTCAGGTATATACCGCCTTGGC'))


if __name__ == '__main__':
    unittest.main()